"""Player metadata: bowling style, batting hand, role, country.

Why this exists
---------------
Cricsheet records who bowled every ball but never what *kind* of bowler they
are, and that single attribute is the hinge the whole matchup analysis turns on.
Without it, "against left-arm wrist spin in the middle overs" is unanswerable and
the strategy planner has nothing to reason with.

Where the data comes from
-------------------------
A published player-metadata table keyed on the Cricsheet person id, so it joins
to ball-by-ball data exactly. The attributes ultimately originate from public
player profiles; see docs/DATA_SOURCES.md for the provenance chain and the
licensing caveat, which is real and worth reading before redistributing.

This module only converts that table into the project's own styles CSV. Nothing
here fetches: the input is a local file, so a build stays reproducible and
offline.
"""
from __future__ import annotations

import csv
from pathlib import Path

from ..styles import normalise_batting_style, normalise_bowling_style

# Columns we understand on the input side. Anything else is ignored.
IN_NAME = "unique_name"
IN_ID = "cricsheet_id"
IN_BOWL = "bowling_style"
IN_BAT = "batting_style"
IN_ROLE = "playing_role"
IN_COUNTRY = "country"
IN_CRICINFO = "cricinfo_id"
IN_FULL = "full_name"
IN_DOB = "dob"

OUT_FIELDS = ["name", "cricsheet_id", "full_name", "bowling_type", "batting_hand", "role",
              "country", "cricinfo_id", "source"]


def _clean(value: str | None) -> str:
    """Blank out the many spellings of "no value" this kind of export uses."""
    if value is None:
        return ""
    text = value.strip().strip('"').strip()
    if text.upper() in {"", "NA", "N/A", "NULL", "NONE", "-"}:
        return ""
    return text


def primary_style(raw: str) -> str:
    """Take the first style from a multi-style cell.

    Profiles record all-rounders as "Right arm Medium, Right arm Offbreak".
    The first entry is the primary one, and taking it matters: the normaliser
    tests spin patterns before pace, so handing it the whole string would file a
    medium-pacer who bowls occasional off spin under off spin.
    """
    return _clean(raw).split(",")[0].strip()


def convert(source: Path, dest: Path) -> dict:
    """Convert a player-metadata CSV into the project's styles CSV."""
    rows = list(csv.DictReader(source.open(encoding="utf-8")))
    out: list[dict] = []
    stats = {"input": len(rows), "written": 0, "withStyle": 0, "withHand": 0,
             "unrecognisedStyles": {}}

    for row in rows:
        name = _clean(row.get(IN_NAME))
        if not name:
            continue
        raw_style = primary_style(row.get(IN_BOWL, ""))
        bowling = normalise_bowling_style(raw_style) if raw_style else ""
        if raw_style and not bowling:
            stats["unrecognisedStyles"][raw_style] = \
                stats["unrecognisedStyles"].get(raw_style, 0) + 1
        hand = normalise_batting_style(_clean(row.get(IN_BAT, "")))

        if not bowling and not hand:
            continue
        out.append({
            "name": name,
            # The person id is what the build joins on; the name is only used
            # when it is missing (see pipeline/enrich.py).
            "cricsheet_id": _clean(row.get(IN_ID)),
            # Cricsheet names players "V Kohli"; people search "Virat Kohli".
            # Carrying the full name is what makes that search work.
            "full_name": _clean(row.get(IN_FULL)),
            "bowling_type": bowling,
            "batting_hand": hand,
            "role": _clean(row.get(IN_ROLE)),
            "country": _clean(row.get(IN_COUNTRY)),
            "cricinfo_id": _clean(row.get(IN_CRICINFO)),
            "source": "player-meta",
        })
        stats["withStyle"] += 1 if bowling else 0
        stats["withHand"] += 1 if hand else 0

    out.sort(key=lambda r: (r["name"], r["cricsheet_id"]))
    dest.parent.mkdir(parents=True, exist_ok=True)
    with dest.open("w", newline="", encoding="utf-8") as fh:
        fh.write(
            "# Generated by pipeline/sources/playermeta.py - do not hand-edit.\n"
            "# Put manual corrections in data/styles.csv instead: that file is\n"
            "# read last and overrides everything here.\n")
        writer = csv.DictWriter(fh, fieldnames=OUT_FIELDS)
        writer.writeheader()
        writer.writerows(out)
    stats["written"] = len(out)
    return stats
